# Generated by Django 2.0 on 2019-04-02 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190401_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaiverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 16, 30, 58, 726789)),
        ),
    ]
