# Generated by Django 2.0 on 2019-04-02 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190401_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaiverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 14, 26, 28, 422055)),
        ),
    ]
